#!/usr/bin/env python3
"""Translate between a clean SysML v2 textual profile and SJS JSON.

The SJS shape is based on SysML_JSON_Schema_Spec_v1.docx.  This tool is
intentionally deterministic: JSON is emitted in a stable key order, null/empty
noise is stripped, and SysML text generated by this tool can be parsed back into
the same SJS model.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from copy import deepcopy
from datetime import date
from pathlib import Path
from typing import Any


TOP_LEVEL_ORDER = [
    "$schema",
    "model_meta",
    "subsystems",
    "item_flows",
    "values",
    "relationships",
    "requirements",
    "behaviour",
    "allocations",
    "constraints",
    "verification",
    "views",
    "lifecycle",
    "provenance",
    "change_history",
]

MODEL_META_ORDER = [
    "system_name",
    "system_id",
    "description",
    "version",
    "lifecycle_stage",
    "domain",
    "maturity",
    "authors",
    "date_modified",
    "context",
]

SUBSYSTEM_ORDER = [
    "subsystem_id",
    "subsystem_name",
    "sysml_equivalent",
    "functional_basis",
    "description",
    "domain",
    "maturity",
    "spatial_region",
    "parts",
    "ports",
    "interfaces",
    "attributes",
    "sub_subsystems",
    "satisfies_requirements",
    "allocated_functions",
    "sysml_qualified_name",
]

OBJECT_ORDERS = {
    "model_meta": MODEL_META_ORDER,
    "subsystems": SUBSYSTEM_ORDER,
    "parts": [
        "item_no",
        "part_id",
        "description",
        "quantity",
        "multiplicity",
        "material",
        "source",
        "sysml_type",
        "sysml_path",
        "attributes",
        "notes",
    ],
    "ports": ["port_id", "name", "direction", "flow_type", "connector_type", "notes"],
    "interfaces": [
        "interface_id",
        "mating_subsystem",
        "port_this",
        "port_mate",
        "flow_ref",
        "shared_parts",
        "interface_type",
        "notes",
    ],
    "item_flows": ["flow_id", "name", "flow_type", "attributes", "notes"],
    "values": ["value_id", "name", "value", "unit", "expression", "source", "notes"],
    "relationships": [
        "relationship_id",
        "type",
        "source",
        "target",
        "context",
        "source_file",
        "notes",
    ],
    "requirements": [
        "req_id",
        "category",
        "priority",
        "statement",
        "rationale",
        "attributes",
        "satisfied_by",
        "verified_by",
        "status",
    ],
    "state_machines": ["sm_id", "name", "owner", "entry_state", "states"],
    "states": ["name", "description", "entry_action", "exit_action", "transitions"],
    "transitions": ["name", "trigger", "guard", "action", "target"],
    "actions": [
        "action_id",
        "name",
        "owner",
        "parameters",
        "steps",
        "preconditions",
        "postconditions",
    ],
    "steps": ["step_no", "description", "duration_ms", "parallel_with"],
    "allocations": ["allocation_id", "type", "from", "to", "rationale"],
    "constraints": ["constraint_id", "name", "expression", "variables", "type", "status"],
    "variables": ["name", "source", "attribute"],
    "views": ["view_id", "name", "viewpoint", "includes", "excludes"],
    "verification": ["verification_cases", "analysis_cases", "test_cases"],
    "verification_cases": ["case_id", "name", "type", "subject", "method", "status", "notes"],
    "analysis_cases": ["case_id", "name", "type", "subject", "method", "status", "notes"],
    "test_cases": ["case_id", "name", "type", "subject", "method", "status", "notes"],
    "lifecycle": ["individuals", "successions", "configurations"],
    "individuals": [
        "individual_id",
        "name",
        "sysml_qualified_name",
        "type",
        "conforms_to",
        "description",
        "attributes",
        "snapshots",
        "timeslices",
    ],
    "snapshots": ["snapshot_id", "name", "sysml_qualified_name", "time_ref", "members", "notes"],
    "timeslices": ["timeslice_id", "name", "sysml_qualified_name", "start_snapshot", "end_snapshot", "members", "notes"],
    "members": ["name", "sysml_qualified_name", "type", "role", "members", "notes"],
    "successions": ["succession_id", "first", "then", "relationship", "owner", "notes"],
    "configurations": ["configuration_id", "individual", "configuration", "valid_during", "snapshots", "notes"],
    "provenance": [
        "translator",
        "translator_version",
        "schema_version",
        "generated_on",
        "source_files",
        "source_packages",
        "mapping_notes",
    ],
    "source_files": ["path", "name", "package", "imports"],
    "imports": ["visibility", "target"],
    "change_history": ["change_id", "timestamp", "actor", "change_type", "summary", "affected_elements", "status"],
}

ATTRIBUTE_TYPES = {
    "mass_kg": (int, float),
    "length_mm": (int, float),
    "width_mm": (int, float),
    "height_mm": (int, float),
    "wall_thickness_mm": (int, float),
    "infill_pct": int,
    "surface_finish": str,
    "yield_strength_mpa": (int, float),
    "max_axial_force_n": (int, float),
    "max_torque_nm": (int, float),
    "stroke_mm": (int, float),
    "lead_mm_rev": (int, float),
    "ip_rating": str,
    "mount_style": str,
    "voltage_v": (int, float),
    "voltage_min_v": (int, float),
    "voltage_max_v": (int, float),
    "current_rated_a": (int, float),
    "current_stall_a": (int, float),
    "current_peak_a": (int, float),
    "current_a": (int, float),
    "power_w": (int, float),
    "resistance_ohm": (int, float),
    "capacitance_uf": (int, float),
    "frequency_hz": (int, float),
    "logic_level_v": (int, float),
    "interface_protocol": str,
    "pwm_frequency_hz": (int, float),
    "bridge_type": str,
    "protection_features": list,
    "motor_type": str,
    "rated_torque_nm": (int, float),
    "no_load_rpm": (int, float),
    "stall_torque_nm": (int, float),
    "kv_rating": (int, float),
    "steps_per_rev": int,
    "gear_ratio": (int, float),
    "encoder_ppr": int,
    "encoder_type": str,
    "efficiency": (int, float),
    "max_speed_ms": (int, float),
    "position_accuracy_mm": (int, float),
    "processor": str,
    "clock_mhz": (int, float),
    "flash_kb": int,
    "ram_kb": int,
    "os": str,
    "loop_rate_hz": (int, float),
    "comm_protocols": list,
    "control_algorithm": str,
    "firmware_version": str,
    "watchdog_timeout_ms": (int, float),
    "sensor_type": str,
    "measurement_range": str,
    "accuracy": str,
    "sample_rate_hz": (int, float),
    "output_type": str,
    "resolution_bits": int,
    "normally_open": bool,
    "max_temp_c": (int, float),
    "min_temp_c": (int, float),
    "thermal_resistance_ckw": (int, float),
    "heat_dissipation_w": (int, float),
    "cooling_method": str,
    "fluid_type": str,
    "operating_pressure_bar": (int, float),
    "max_pressure_bar": (int, float),
    "flow_rate_lpm": (int, float),
    "viscosity_cst": (int, float),
    "sealing_standard": str,
    "torque_nm": (int, float),
    "speed_ms": (int, float),
    "pressure_bar": (int, float),
    "temp_c": (int, float),
    "data_rate_kbps": (int, float),
    "message_format": str,
}

REQUIRED_TOP_LEVEL = {"$schema", "model_meta", "subsystems"}
REQUIRED_META = {"system_name", "system_id", "description", "version", "lifecycle_stage", "domain", "maturity"}
REQUIRED_SUBSYSTEM = {"subsystem_id", "subsystem_name", "description", "domain"}


class TranslationError(ValueError):
    """Raised when a model cannot be translated or validated."""


def clean(value: Any, *, keep_empty_top: bool = False) -> Any:
    """Remove nulls and empty containers to keep LLM-facing JSON sparse."""
    if isinstance(value, dict):
        out = {}
        for key, item in value.items():
            cleaned = clean(item)
            if cleaned is None or cleaned == "" or cleaned == [] or cleaned == {}:
                continue
            out[key] = cleaned
        return out
    if isinstance(value, list):
        return [item for item in (clean(v) for v in value) if item not in (None, "", [], {})]
    return value


def ordered(value: Any, context: str | None = None) -> Any:
    if isinstance(value, list):
        child_context = singular_context(context)
        return [ordered(item, child_context) for item in value]
    if not isinstance(value, dict):
        return value

    if context is None:
        keys = TOP_LEVEL_ORDER
    else:
        keys = OBJECT_ORDERS.get(context, [])

    result: dict[str, Any] = {}
    for key in keys:
        if key in value:
            result[key] = ordered(value[key], key)
    for key in sorted(k for k in value if k not in result):
        result[key] = ordered(value[key], key)
    return result


def singular_context(context: str | None) -> str | None:
    if context == "subsystems":
        return "subsystems"
    if context in {"parts", "ports", "interfaces", "requirements", "item_flows", "allocations", "constraints", "views"}:
        return context
    if context in {"states", "transitions", "actions", "steps", "variables"}:
        return context
    return context


def canonicalize(model: dict[str, Any]) -> dict[str, Any]:
    model = clean(deepcopy(model))
    model.setdefault("$schema", "sjs/1.0")
    model.setdefault("model_meta", {})
    model.setdefault("subsystems", [])
    return ordered(model)


def dumps_canonical(model: dict[str, Any]) -> str:
    return json.dumps(canonicalize(model), indent=2, ensure_ascii=False) + "\n"


def validate(model: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    missing_top = REQUIRED_TOP_LEVEL - model.keys()
    for key in sorted(missing_top):
        errors.append(f"missing top-level key: {key}")

    meta = model.get("model_meta", {})
    if not isinstance(meta, dict):
        errors.append("model_meta must be an object")
    else:
        for key in sorted(REQUIRED_META - meta.keys()):
            errors.append(f"model_meta.{key} is required")

    subsystems = model.get("subsystems", [])
    if not isinstance(subsystems, list):
        errors.append("subsystems must be an array")
        subsystems = []
    for index, subsystem in enumerate(subsystems):
        if not isinstance(subsystem, dict):
            errors.append(f"subsystems[{index}] must be an object")
            continue
        label = subsystem.get("subsystem_id", index)
        for key in sorted(REQUIRED_SUBSYSTEM - subsystem.keys()):
            errors.append(f"subsystem {label}: {key} is required")
        validate_attributes(subsystem.get("attributes", {}), f"subsystem {label}", errors)
        for p_index, part in enumerate(subsystem.get("parts", [])):
            if not isinstance(part, dict):
                errors.append(f"subsystem {label}: parts[{p_index}] must be an object")
                continue
            for key in ["part_id", "description", "quantity"]:
                if key not in part:
                    errors.append(f"part in subsystem {label}: {key} is required")
            validate_attributes(part.get("attributes", {}), f"part {part.get('part_id', p_index)}", errors)

    return errors


def validate_attributes(attributes: Any, label: str, errors: list[str]) -> None:
    if not attributes:
        return
    if not isinstance(attributes, dict):
        errors.append(f"{label}: attributes must be an object")
        return
    for key, value in attributes.items():
        expected = ATTRIBUTE_TYPES.get(key)
        if expected is None:
            errors.append(f"{label}: unknown attribute '{key}'")
        elif expected is bool:
            if type(value) is not bool:
                errors.append(f"{label}: attribute '{key}' must be Boolean")
        elif expected is int:
            if type(value) is not int:
                errors.append(f"{label}: attribute '{key}' must be Integer")
        elif expected is list:
            if not isinstance(value, list):
                errors.append(f"{label}: attribute '{key}' must be an array")
        elif not isinstance(value, expected):
            errors.append(f"{label}: attribute '{key}' has invalid type")


def ensure_valid(model: dict[str, Any]) -> None:
    errors = validate(model)
    if errors:
        raise TranslationError("SJS validation failed:\n- " + "\n- ".join(errors))


def identifier(text: str, fallback: str = "Element") -> str:
    text = re.sub(r"[^A-Za-z0-9_]+", "_", text or "").strip("_")
    if not text:
        text = fallback
    if text[0].isdigit():
        text = "_" + text
    return text


def q(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def sysml_from_sjs(model: dict[str, Any]) -> str:
    model = canonicalize(model)
    ensure_valid(model)
    meta = model["model_meta"]
    package_name = identifier(meta.get("system_name") or meta.get("system_id") or "SJSModel")
    lines = [
        f"package {package_name} {{",
        f"  @sjs.schema {q({'$schema': model.get('$schema', 'sjs/1.0')})}",
        f"  @sjs.meta {q(meta)}",
    ]

    for flow in model.get("item_flows", []):
        lines.extend(render_item_flow(flow))
    for value in model.get("values", []):
        lines.extend(render_value(value))
    for subsystem in model.get("subsystems", []):
        lines.extend(render_subsystem(subsystem, level=1))
    for relationship in model.get("relationships", []):
        lines.extend(render_relationship(relationship))
    for requirement in model.get("requirements", []):
        lines.extend(render_requirement(requirement))

    behaviour = model.get("behaviour", {})
    for state_machine in behaviour.get("state_machines", []):
        lines.extend(render_state_machine(state_machine))
    for action in behaviour.get("actions", []):
        lines.extend(render_action(action))
    for allocation in model.get("allocations", []):
        lines.append(f"  allocate {identifier(allocation.get('allocation_id', 'Allocation'))} {{ @sjs {q(allocation)} }}")
    for constraint in model.get("constraints", []):
        lines.extend(render_constraint(constraint))
    if model.get("verification"):
        lines.extend(render_verification(model["verification"]))
    for view in model.get("views", []):
        lines.append(f"  view def {identifier(view.get('name') or view.get('view_id') or 'View')} {{ @sjs {q(view)} }}")
    if model.get("lifecycle"):
        lines.extend(render_lifecycle(model["lifecycle"]))
    if model.get("provenance"):
        lines.extend(render_provenance(model["provenance"]))
    for change in model.get("change_history", []):
        lines.extend(render_change(change))

    lines.append("}")
    return "\n".join(lines) + "\n"


def render_item_flow(flow: dict[str, Any]) -> list[str]:
    name = identifier(flow.get("name") or flow.get("flow_id") or "ItemFlow")
    return [f"  item def {name} {{ @sjs {q(flow)} }}"]


def render_value(value: dict[str, Any]) -> list[str]:
    name = identifier(value.get("name") or value.get("value_id") or "Value")
    rendered_value = value.get("value")
    unit = value.get("unit")
    if rendered_value is not None:
        suffix = f" [{unit}]" if unit else ""
        return [f"  attribute {name} = {q(rendered_value)}{suffix} {{ @sjs {q(value)} }}"]
    return [f"  attribute def {name} {{ @sjs {q(value)} }}"]


def render_subsystem(subsystem: dict[str, Any], level: int) -> list[str]:
    indent = "  " * level
    name = identifier(subsystem.get("subsystem_name") or subsystem.get("subsystem_id") or "Subsystem")
    sysml_equivalent = str(subsystem.get("sysml_equivalent", "part def")).strip().lower()
    keyword = "part" if sysml_equivalent in {"part", "part usage", "part instance"} else "part def"
    lines = [f"{indent}{keyword} {name} {{", f"{indent}  @sjs {q(strip_children(subsystem))}"]
    for port in subsystem.get("ports", []):
        direction = {"in": "in", "out": "out", "inout": "inout"}.get(port.get("direction"), "inout")
        lines.append(f"{indent}  {direction} port {identifier(port.get('name') or port.get('port_id') or 'port')} {{ @sjs {q(port)} }}")
    for part in subsystem.get("parts", []):
        lines.append(f"{indent}  part {identifier(part.get('description') or part.get('part_id') or 'part')} {{ @sjs {q(part)} }}")
    for interface in subsystem.get("interfaces", []):
        lines.append(f"{indent}  connect {identifier(interface.get('interface_id', 'Interface'))} {{ @sjs {q(interface)} }}")
    for child in subsystem.get("sub_subsystems", []):
        lines.extend(render_subsystem(child, level + 1))
    lines.append(f"{indent}}}")
    return lines


def strip_children(subsystem: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in subsystem.items() if k not in {"parts", "ports", "interfaces", "sub_subsystems"}}


def render_relationship(relationship: dict[str, Any]) -> list[str]:
    name = identifier(relationship.get("relationship_id") or relationship.get("type") or "Relationship")
    rel_type = str(relationship.get("type", "dependency")).lower()
    keyword = "succession" if rel_type == "succession" else "dependency"
    return [f"  {keyword} {name} {{ @sjs {q(relationship)} }}"]


def render_requirement(requirement: dict[str, Any]) -> list[str]:
    name = identifier(requirement.get("req_id") or "Requirement")
    statement = requirement.get("statement")
    if statement:
        return [f"  requirement def {name} {{", f"    doc {q(statement)}", f"    @sjs {q(requirement)}", "  }"]
    return [f"  requirement def {name} {{ @sjs {q(requirement)} }}"]


def render_state_machine(state_machine: dict[str, Any]) -> list[str]:
    name = identifier(state_machine.get("name") or state_machine.get("sm_id") or "StateMachine")
    return [f"  state def {name} {{ @sjs {q(state_machine)} }}"]


def render_action(action: dict[str, Any]) -> list[str]:
    name = identifier(action.get("name") or action.get("action_id") or "Action")
    return [f"  action def {name} {{ @sjs {q(action)} }}"]


def render_constraint(constraint: dict[str, Any]) -> list[str]:
    name = identifier(constraint.get("name") or constraint.get("constraint_id") or "Constraint")
    expression = constraint.get("expression", "true")
    return [f"  constraint def {name} {{", f"    assert {q(expression)}", f"    @sjs {q(constraint)}", "  }"]


def render_verification(verification: dict[str, Any]) -> list[str]:
    return [
        "  package Verification {",
        f"    @sjs {q(verification)}",
        "  }",
    ]


def render_lifecycle(lifecycle: dict[str, Any]) -> list[str]:
    lines = ["  package Lifecycle {", f"    @sjs {q(lifecycle)}"]
    for individual in lifecycle.get("individuals", []):
        name = identifier(individual.get("name") or individual.get("individual_id") or "Individual")
        lines.append(f"    individual part {name} {{ @sjs {q(individual)} }}")
    for succession in lifecycle.get("successions", []):
        name = identifier(succession.get("succession_id") or "Succession")
        lines.append(f"    succession {name} {{ @sjs {q(succession)} }}")
    for configuration in lifecycle.get("configurations", []):
        name = identifier(configuration.get("configuration_id") or "Configuration")
        lines.append(f"    part {name} {{ @sjs {q(configuration)} }}")
    lines.append("  }")
    return lines


def render_provenance(provenance: dict[str, Any]) -> list[str]:
    return [
        "  metadata def SJSProvenance {",
        f"    @sjs {q(provenance)}",
        "  }",
    ]


def render_change(change: dict[str, Any]) -> list[str]:
    name = identifier(change.get("change_id") or "Change")
    return [f"  metadata def {name} {{ @sjs {q(change)} }}"]


def sjs_from_sysml(text: str) -> dict[str, Any]:
    """Parse the SJS SysML profile.

    The parser accepts SysML v2-style elements that carry @sjs JSON payloads.
    For hand-written partial files, it also extracts package name and doc text.
    """
    payloads = extract_sjs_payloads(text)
    if not payloads:
        model = sjs_from_plain_sysml(text)
        model = canonicalize(model)
        ensure_valid(model)
        return model

    model: dict[str, Any] = {"$schema": "sjs/1.0", "model_meta": {}, "subsystems": []}
    behaviour: dict[str, list[Any]] = {"state_machines": [], "actions": []}

    for kind, payload in payloads:
        if kind == "schema" and "$schema" in payload:
            model["$schema"] = payload["$schema"]
        elif kind == "meta":
            model["model_meta"] = payload
        elif is_subsystem_payload(payload):
            subsystem = deepcopy(payload)
            subsystem.setdefault("parts", [])
            subsystem.setdefault("ports", [])
            subsystem.setdefault("interfaces", [])
            subsystem.setdefault("sub_subsystems", [])
            model["subsystems"].append(subsystem)
        elif "flow_id" in payload:
            model.setdefault("item_flows", []).append(payload)
        elif "value_id" in payload:
            model.setdefault("values", []).append(payload)
        elif "relationship_id" in payload:
            model.setdefault("relationships", []).append(payload)
        elif "req_id" in payload:
            model.setdefault("requirements", []).append(payload)
        elif "sm_id" in payload:
            behaviour["state_machines"].append(payload)
        elif "action_id" in payload:
            behaviour["actions"].append(payload)
        elif "allocation_id" in payload:
            model.setdefault("allocations", []).append(payload)
        elif "constraint_id" in payload:
            model.setdefault("constraints", []).append(payload)
        elif any(key in payload for key in ("verification_cases", "analysis_cases", "test_cases")):
            model["verification"] = payload
        elif "view_id" in payload:
            model.setdefault("views", []).append(payload)
        elif any(key in payload for key in ("individuals", "successions", "configurations")):
            model["lifecycle"] = payload
        elif "translator" in payload and "source_files" in payload:
            model["provenance"] = payload
        elif "change_id" in payload:
            model.setdefault("change_history", []).append(payload)

    attach_child_payloads(text, model)
    if behaviour["state_machines"] or behaviour["actions"]:
        model["behaviour"] = clean(behaviour)
    fill_meta_from_plain_sysml(text, model)
    model = canonicalize(model)
    ensure_valid(model)
    return model


def sjs_from_plain_sysml(text: str) -> dict[str, Any]:
    """Import a practical subset of plain SysML v2 textual notation.

    This covers common early MBSE files: package declarations, port defs,
    interface defs, part defs with attributes/ports/actions/states, and assembly
    part usages.  Unknown SysML detail is summarized in notes instead of being
    forced into noisy or invalid SJS fields.
    """
    package_name = plain_package_name(text)
    model: dict[str, Any] = {
        "$schema": "sjs/1.0",
        "model_meta": {
            "system_name": split_name(package_name),
            "system_id": identifier(package_name).upper(),
            "description": f"Imported from SysML v2 package {package_name}.",
            "version": "0.1.0",
            "lifecycle_stage": "concept",
            "domain": "systems",
            "maturity": "draft",
            "date_modified": date.today().isoformat(),
        },
        "subsystems": [],
    }

    port_defs = parse_port_defs(text)
    interface_defs = parse_interface_defs(text)
    part_defs = parse_part_defs(text)
    actions: list[dict[str, Any]] = []
    state_machines: list[dict[str, Any]] = []

    for index, part_def in enumerate(part_defs, start=1):
        subsystem_id = f"SS-{index:02d}"
        subsystem = subsystem_from_part_def(part_def, subsystem_id, port_defs)
        model["subsystems"].append(subsystem)

        for action_name in part_def["actions"]:
            actions.append(
                {
                    "action_id": f"ACT-{len(actions) + 1:03d}",
                    "name": action_name,
                    "owner": subsystem_id,
                    "steps": [{"step_no": 1, "description": f"Perform {split_name(action_name)}."}],
                }
            )
        for state_machine in parse_state_machines(part_def["body"], subsystem_id):
            state_machine["sm_id"] = f"SM-{len(state_machines) + 1:03d}"
            state_machines.append(state_machine)

    assembly_parts = parse_assembly_parts(text)
    if assembly_parts:
        model["subsystems"].append(assembly_subsystem(package_name, len(model["subsystems"]) + 1, assembly_parts))

    item_flows = item_flows_from_port_defs(port_defs)
    if item_flows:
        model["item_flows"] = item_flows
    interfaces = interfaces_from_defs(interface_defs)
    if interfaces and model["subsystems"]:
        model["subsystems"][0].setdefault("interfaces", []).extend(interfaces)
    if actions or state_machines:
        model["behaviour"] = clean({"state_machines": state_machines, "actions": actions})

    return model


def plain_package_name(text: str) -> str:
    match = re.search(r"\bpackage\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{", text)
    return match.group(1) if match else "UnnamedSystem"


def split_name(name: str) -> str:
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", name)
    return spaced.replace("_", " ").strip()


def parse_blocks(text: str, pattern: str) -> list[dict[str, str]]:
    blocks: list[dict[str, str]] = []
    regex = re.compile(pattern, re.M)
    for match in regex.finditer(text):
        start = match.end() - 1
        end = matching_brace(text, start)
        if end < 0:
            continue
        blocks.append({"name": match.group("name"), "body": text[start + 1 : end], "start": str(start), "end": str(end)})
    return blocks


def parse_port_defs(text: str) -> dict[str, dict[str, str]]:
    port_defs: dict[str, dict[str, str]] = {}
    for block in parse_blocks(text, r"\bport\s+def\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\{"):
        direction = "inout"
        flow_name = block["name"]
        sysml_type = ""
        for line in block["body"].splitlines():
            match = re.search(r"\b(in|out)\s+([A-Za-z_][A-Za-z0-9_]*)(?:\s*:>\s*([^;]+))?\s*;", line.strip())
            if match:
                direction, flow_name, sysml_type = match.group(1), match.group(2), (match.group(3) or "")
                break
        port_defs[block["name"]] = {
            "direction": direction,
            "flow_name": flow_name,
            "sysml_type": sysml_type.strip(),
            "flow_type": infer_flow_type(flow_name, sysml_type),
        }
    return port_defs


def infer_flow_type(name: str, sysml_type: str = "") -> str:
    text = f"{name} {sysml_type}".lower()
    if "length" in text or "extension" in text or "linear" in text:
        return "mechanical_linear"
    if "torque" in text or "angular" in text or "shaft" in text:
        return "mechanical_rotary"
    if "power" in text or "voltage" in text or "current" in text:
        return "electrical_power"
    if "signal" in text or "control" in text:
        return "signal_digital"
    return "data_digital"


def parse_interface_defs(text: str) -> list[dict[str, Any]]:
    interfaces: list[dict[str, Any]] = []
    for block in parse_blocks(text, r"\binterface\s+def\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\{"):
        flows = re.findall(r"\bflow\s+([^;]+?)\s+to\s+([^;]+?)\s*;", block["body"])
        interfaces.append({"name": block["name"], "flows": flows})
    return interfaces


def parse_part_defs(text: str) -> list[dict[str, Any]]:
    part_defs: list[dict[str, Any]] = []
    for block in parse_blocks(text, r"\bpart\s+def\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\{"):
        body = block["body"]
        attributes = re.findall(r"\battribute\s+([A-Za-z_][A-Za-z0-9_]*)(?:\s*:>\s*([^;]+))?\s*;", body)
        ports = re.findall(r"\bport\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([A-Za-z_][A-Za-z0-9_]*)\s*;", body)
        actions = re.findall(r"\bperform\s+action\s+([A-Za-z_][A-Za-z0-9_]*)\s*;", body)
        part_defs.append({"name": block["name"], "body": body, "attributes": attributes, "ports": ports, "actions": actions})
    return part_defs


def subsystem_from_part_def(part_def: dict[str, Any], subsystem_id: str, port_defs: dict[str, dict[str, str]]) -> dict[str, Any]:
    name = part_def["name"]
    subsystem: dict[str, Any] = {
        "subsystem_id": subsystem_id,
        "subsystem_name": split_name(name),
        "sysml_equivalent": "part def",
        "functional_basis": [split_name(action) for action in part_def["actions"]],
        "description": f"Imported SysML part definition {name}.",
        "domain": infer_domain(name, part_def),
        "maturity": "draft",
        "ports": [],
    }
    if part_def["attributes"]:
        declared = [f"{attr[0]} :> {attr[1].strip()}" if attr[1] else attr[0] for attr in part_def["attributes"]]
        subsystem["notes"] = "Declared SysML attributes without values: " + "; ".join(declared)
    for p_index, (port_name, port_type) in enumerate(part_def["ports"], start=1):
        definition = port_defs.get(port_type, {})
        subsystem["ports"].append(
            {
                "port_id": f"PT-{subsystem_id[3:]}{p_index:02d}",
                "name": port_name,
                "direction": definition.get("direction", "inout"),
                "flow_type": definition.get("flow_type", "data_digital"),
                "notes": f"SysML port type: {port_type}",
            }
        )
    return subsystem


def infer_domain(name: str, part_def: dict[str, Any]) -> str:
    text = " ".join([name, *part_def.get("actions", []), *[p[0] for p in part_def.get("ports", [])]]).lower()
    if "motor" in text or "torque" in text or "gear" in text:
        return "electromechanical"
    if "control" in text or "signal" in text or "switch" in text or "pcb" in text or "wire" in text:
        return "software"
    if "shaft" in text or "housing" in text:
        return "mechanical"
    return "systems"


def parse_state_machines(body: str, owner: str) -> list[dict[str, Any]]:
    machines: list[dict[str, Any]] = []
    for block in parse_blocks(body, r"\bstate\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\{"):
        states: list[dict[str, Any]] = []
        for state_name in re.findall(r"\bstate\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:;|\{)", block["body"]):
            if state_name == block["name"]:
                continue
            state = {"name": state_name, "description": f"Imported SysML state {state_name}."}
            nested_match = re.search(rf"\bstate\s+{re.escape(state_name)}\s*\{{", block["body"])
            if nested_match:
                start = nested_match.end() - 1
                end = matching_brace(block["body"], start)
                nested = block["body"][start + 1 : end] if end >= 0 else ""
                entry = re.search(r"\bentry\s+([A-Za-z_][A-Za-z0-9_]*)\s*;", nested)
                do = re.search(r"\bdo\s+([A-Za-z_][A-Za-z0-9_]*)\s*;", nested)
                exit_action = re.search(r"\bexit\s+([A-Za-z_][A-Za-z0-9_]*)\s*;", nested)
                if entry:
                    state["entry_action"] = entry.group(1)
                if do:
                    state["do_action"] = do.group(1)
                if exit_action:
                    state["exit_action"] = exit_action.group(1)
            states.append(state)
        machines.append(
            {
                "name": split_name(block["name"]),
                "owner": owner,
                "entry_state": states[0]["name"] if states else "",
                "states": states,
            }
        )
    return machines


def parse_assembly_parts(text: str) -> list[dict[str, str]]:
    blocks = parse_blocks(text, r"\bpart\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\{")
    if not blocks:
        return []
    assembly = max(blocks, key=lambda b: len(re.findall(r"\bpart\s+[A-Za-z_][A-Za-z0-9_]*\s*:", b["body"])))
    parts = []
    for name, type_name in re.findall(r"\bpart\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([A-Za-z_][A-Za-z0-9_]*)\s*;", assembly["body"]):
        parts.append({"name": name, "type": type_name})
    return parts


def assembly_subsystem(package_name: str, index: int, assembly_parts: list[dict[str, str]]) -> dict[str, Any]:
    subsystem = {
        "subsystem_id": f"SS-{index:02d}",
        "subsystem_name": split_name(package_name).replace(" Model", " Assembly"),
        "sysml_equivalent": "part",
        "description": "Imported top-level SysML assembly containing part usages.",
        "domain": "electromechanical",
        "maturity": "draft",
        "parts": [],
    }
    for p_index, part in enumerate(assembly_parts, start=1):
        subsystem["parts"].append(
            {
                "item_no": str(p_index),
                "part_id": f"P-{p_index:03d}",
                "description": split_name(part["name"]),
                "quantity": 1,
                "material": part["type"],
                "source": "unspecified",
                "notes": f"SysML type: {part['type']}",
            }
        )
    return subsystem


def item_flows_from_port_defs(port_defs: dict[str, dict[str, str]]) -> list[dict[str, Any]]:
    flows = []
    seen = set()
    for definition in port_defs.values():
        flow_name = definition.get("flow_name") or "Flow"
        if flow_name in seen:
            continue
        seen.add(flow_name)
        flows.append(
            {
                "flow_id": f"FL-{len(flows) + 1:03d}",
                "name": split_name(flow_name).replace(" ", ""),
                "flow_type": definition.get("flow_type", "data_digital"),
                "notes": f"Imported from SysML port item {flow_name}.",
            }
        )
    return flows


def interfaces_from_defs(interface_defs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    interfaces = []
    for interface_def in interface_defs:
        for left, right in interface_def["flows"]:
            interfaces.append(
                {
                    "interface_id": f"IF-{len(interfaces) + 1:03d}",
                    "mating_subsystem": "unresolved",
                    "port_this": left.strip(),
                    "port_mate": right.strip(),
                    "interface_type": "data_bus" if "signal" in left.lower() else "mechanical_fastened",
                    "notes": f"Imported from SysML interface def {interface_def['name']}.",
                }
            )
    return interfaces


def extract_sjs_payloads(text: str) -> list[tuple[str, dict[str, Any]]]:
    payloads: list[tuple[str, dict[str, Any]]] = []
    marker = "@sjs"
    index = 0
    while True:
        start = text.find(marker, index)
        if start < 0:
            break
        after = start + len(marker)
        kind = "element"
        if text[after : after + 5] == ".meta":
            kind = "meta"
            after += 5
        elif text[after : after + 7] == ".schema":
            kind = "schema"
            after += 7
        brace = text.find("{", after)
        if brace < 0:
            break
        end = matching_brace(text, brace)
        if end < 0:
            raise TranslationError("unterminated @sjs JSON payload")
        raw = text[brace : end + 1]
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise TranslationError(f"invalid @sjs JSON payload at offset {brace}: {exc}") from exc
        payloads.append((kind, payload))
        index = end + 1
    return payloads


def matching_brace(text: str, start: int) -> int:
    depth = 0
    in_string = False
    escape = False
    for index in range(start, len(text)):
        char = text[index]
        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return index
    return -1


def is_subsystem_payload(payload: dict[str, Any]) -> bool:
    return "subsystem_id" in payload or "subsystem_name" in payload


def attach_child_payloads(text: str, model: dict[str, Any]) -> None:
    """Attach part/port/connect payloads to nearest containing part def.

    This keeps round-tripping stable even though the top-level extraction also
    sees children as independent @sjs objects.
    """
    systems = {s.get("subsystem_id"): s for s in model.get("subsystems", []) if s.get("subsystem_id")}
    if not systems:
        return

    for subsystem in systems.values():
        subsystem["parts"] = []
        subsystem["ports"] = []
        subsystem["interfaces"] = []

    pattern = re.compile(r"(?:part\s+def|part)\s+[A-Za-z_][A-Za-z0-9_]*\s*\{", re.M)
    for match in pattern.finditer(text):
        body_start = match.end() - 1
        body_end = matching_brace(text, body_start)
        if body_end < 0:
            continue
        body = text[body_start + 1 : body_end]
        own_payloads = extract_sjs_payloads(body)
        if not own_payloads:
            continue
        owner = next((payload for _, payload in own_payloads if is_subsystem_payload(payload)), None)
        if not owner:
            continue
        subsystem = systems.get(owner.get("subsystem_id"))
        if not subsystem:
            continue
        for _, payload in own_payloads:
            if "part_id" in payload:
                subsystem["parts"].append(payload)
            elif "port_id" in payload:
                subsystem["ports"].append(payload)
            elif "interface_id" in payload:
                subsystem["interfaces"].append(payload)


def fill_meta_from_plain_sysml(text: str, model: dict[str, Any]) -> None:
    meta = model.setdefault("model_meta", {})
    package = re.search(r"\bpackage\s+([A-Za-z_][A-Za-z0-9_]*)", text)
    meta.setdefault("system_name", package.group(1) if package else "UnnamedSystem")
    meta.setdefault("system_id", identifier(meta["system_name"]).upper())
    meta.setdefault("description", first_doc(text) or "No description provided.")
    meta.setdefault("version", "0.1.0")
    meta.setdefault("lifecycle_stage", "concept")
    meta.setdefault("domain", "systems")
    meta.setdefault("maturity", "draft")
    meta.setdefault("date_modified", date.today().isoformat())


def first_doc(text: str) -> str | None:
    match = re.search(r"\bdoc\s+(\"(?:\\.|[^\"])*\")", text)
    if not match:
        return None
    try:
        return json.loads(match.group(1))
    except json.JSONDecodeError:
        return None


def command_json_to_sysml(args: argparse.Namespace) -> None:
    model = json.loads(Path(args.input).read_text(encoding="utf-8"))
    text = sysml_from_sjs(model)
    write_output(args.output, text)


def command_sysml_to_json(args: argparse.Namespace) -> None:
    text = Path(args.input).read_text(encoding="utf-8")
    model = sjs_from_sysml(text)
    write_output(args.output, dumps_canonical(model))


def command_clean(args: argparse.Namespace) -> None:
    model = json.loads(Path(args.input).read_text(encoding="utf-8"))
    model = canonicalize(model)
    ensure_valid(model)
    write_output(args.output, dumps_canonical(model))


def command_validate(args: argparse.Namespace) -> None:
    model = json.loads(Path(args.input).read_text(encoding="utf-8"))
    errors = validate(canonicalize(model))
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
    print("valid")


def write_output(path: str | None, text: str) -> None:
    if path:
        Path(path).write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Translate between SysML v2 SJS profile text and clean SJS JSON.")
    sub = parser.add_subparsers(required=True)

    p_json = sub.add_parser("json-to-sysml", help="Convert SJS JSON to SysML v2 SJS-profile text.")
    p_json.add_argument("input")
    p_json.add_argument("-o", "--output")
    p_json.set_defaults(func=command_json_to_sysml)

    p_sysml = sub.add_parser("sysml-to-json", help="Convert SysML v2 SJS-profile text to canonical SJS JSON.")
    p_sysml.add_argument("input")
    p_sysml.add_argument("-o", "--output")
    p_sysml.set_defaults(func=command_sysml_to_json)

    p_clean = sub.add_parser("clean", help="Canonicalize SJS JSON and remove null/empty noise.")
    p_clean.add_argument("input")
    p_clean.add_argument("-o", "--output")
    p_clean.set_defaults(func=command_clean)

    p_validate = sub.add_parser("validate", help="Validate SJS JSON against the embedded schema rules.")
    p_validate.add_argument("input")
    p_validate.set_defaults(func=command_validate)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        args.func(args)
    except TranslationError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())